{% set name = "jsonyx" %}
{% set version = "2.0.0.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3717edb6dd6b0db365b8983d74999f36de3e0a38fc82313b8495594d3a8d6a03

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - jsonyx
    - jsonyx.allow
    - jsonyx.test
  requires:
    - pip
    - pytest
  commands:
    - pip check

about:
  home: https://github.com/nineteendo/jsonyx
  summary: 'Robust JSON manipulator for Python'
  description: |
    `jsonyx` is a robust JSON <http://json.org> manipulator for Python 3.10+.
    It is written in pure Python with an optional C extension for better
    performance and no dependencies
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://jsonyx.readthedocs.io
  dev_url: https://github.com/nineteendo/jsonyx

extra:
  recipe-maintainers:
    - nineteendo
