{% set name = "jsonyx" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 77b14b32aaf1f2f77b997114d8dcaebd91885b7562b0718687e4e571ddbfb762

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - jsonyx
    - jsonyx.allow
    - jsonyx.test
  requires:
    - pip
    - pytest
  commands:
    - pip check

about:
  home: https://github.com/nineteendo/jsonyx
  summary: 'Customizable JSON library for Python'
  description: |
    `jsonyx` is a customizable [JSON](http://json.org) library for Python 3.8+.
    It is written in pure Python with an optional C extension for better
    performance and no dependencies
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://jsonyx.readthedocs.io
  dev_url: https://github.com/nineteendo/jsonyx

extra:
  recipe-maintainers:
    - nineteendo
